# Fichero .ini que contiene las credenciales de acceso a HARICA-ACME
# tal y como aparecen en la web de Harica CertManager
#
# se pueden declarar varios usuarios. 
# Si no se define usuario en la linea de comandos
# se usan las credenciales del usuario "default"
#
[default]
acme_kid = "ACME EAB user identification key"
acme_hmac_key = "ACME EAB user hmac key"
acme_server = "https://acme-v02.harica.gr/acme/codigo_del_usuario/directory"
acme_email = "direccion.de.correo@upm.es"
#
[user1]
acme_kid = ""
acme_hmac_key = ""
acme_server = ""
acme_email = ""
# ...
[user2]
# ...
#

