# Fichero .ini que contiene los datos de DDNS 
# y de ubicacion para cada certificado
# 
# la seccion "default" contiene definiciones globales
# que se aplican a todas las secciones, salvo que sean sobreescritas
[default]
# Fichero requerido por el plugin certbot-dns-rfc2136
# que contiene los datos acceder al servidor por DDNS
dns_credentials = "path-to-ddns-key-file.ini"
# Ubicacion de cada elemento del certificado en el host destino
# Si no están definidos, el certificado no se intenta distribuir
key_path = "/etc/ssl/private/
cert_path = "/etc/ssl/certs/
chain_path = "/usr/share/ca-certificates/

#
# Lista de certificados que se gestionan
#
# Nombre (CN) del certificado
[name.dit.upm.es]
# Nombre del host en el que se va a ubicar el certificado. (Requerido)
cert_host = "host.domain.upm.es"
# Lista separada por comas de SubjectAlternativeName. (Opcional)
# certbot siempre incluye el CN en esta lista
# NO se permiten wildcards
cert_alt_names = ""
# Entrada activa (1) o inactiva (0). (Requerido)
cert_enabled = 0
#
#
[www.lab.dit.upm.es]
cert_host = "host.domain.upm.es"
cert_alt_names = ""
cert_enabled = 0

